name: resonance_music
description: A privacy-first, adaptive music player with explainable on-device recommendations.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
